name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGION: 'australiaeast'
  ACR_NAME: 'skilltechregistry'
  RESOURCE_GROUP_NAME: 'microservices-demo-rg'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Set timeout to 60 minutes
    strategy:
      matrix:
        service:
          - src/adservice
          - src/cartservice
          - src/checkoutservice
          - src/currencyservice
          - src/emailservice
          - src/frontend
          - src/loadgenerator
          - src/paymentservice
          - src/productcatalogservice
          - src/recommendationservice
          - src/shippingservice
          - src/shoppingassistantservice
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ env.ACR_NAME }}.azurecr.io/$(basename ${{ matrix.service }})
          docker build -t $IMAGE_NAME:latest -f ${{ matrix.service }}/Dockerfile . # Build from the root of the repository
          docker push $IMAGE_NAME:latest

      - name: Azure CLI logout
        run: |
          az logout
