name: Deploy to AKS

on:
  push:
    branches:
      - dev
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

env:
  AKS_NAMESPACE: 'default' # Replace if you use a different namespace
  ACR_NAME: 'skilltechregistry'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group microservices-demo-rg --name microservices-demo-aks --overwrite-existing

      - name: Deploy all services
        run: |
          echo "Deploying all services using release/kubernetes-manifests.yaml"
          kubectl apply -f release/kubernetes-manifests.yaml

      - name: Update image tag
        run: |
          echo "Updating image tags for all services to ${{ github.event.inputs.image_tag }}"

          # Use the correct container name(s) from your currencyservice manifest
          kubectl set image deployment/currencyservice <actual-container-name-in-currencyservice-yaml>=${{ env.ACR_NAME }}.azurecr.io/currencyservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }} 

          # ... (other kubectl set image commands, ensure correct container names)

      - name: Azure CLI logout
        run: |
          az logout
