name: Deploy to AKS

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  AKS_NAMESPACE: 'default' # Replace if you use a different namespace

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy each image
        run: |
          for service in ${{ inputs.images }}; do
            echo "Deploying $service"
            kubectl apply -f kubernetes-manifests/$service.yaml 
            kubectl wait --for=condition=available deployment/$service --timeout=60s --namespace ${{ env.AKS_NAMESPACE }} # Wait for deployment to be available
            sleep 10 

            # Ensure to use the correct container name 'server'
            if [ "$service" == "cartservice" ]; then
              kubectl set image deployment/cartservice server=skilltechregistry.azurecr.io/cartservice:latest --namespace ${{ env.AKS_NAMESPACE }}
            else
              kubectl set image deployment/$service server=skilltechregistry.azurecr.io/$service:latest --namespace ${{ env.AKS_NAMESPACE }}
            fi
            
            echo "Deployed $service"
          done
