name: Deploy to AKS

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  AKS_NAMESPACE: 'default' # Replace if you use a different namespace

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Deploy each image
        run: |
          for service in ${{ inputs.images }}; do
            echo "Deploying $service"
            kubectl apply -f kubernetes-manifests/$service.yaml 
            kubectl set image deployment/$service $service=${{ secrets.ACR_NAME }}.azurecr.io/$service:latest --namespace ${{ env.AKS_NAMESPACE }}
            echo "Deployed $service"
          done

      - name: Azure CLI logout
        run: |
          az logout
