name: Deploy to AKS

on:
  workflow_call:
    inputs:
      images:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

env:
  AKS_NAMESPACE: 'default' # Replace if you use a different namespace

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP_NAME }} --name ${{ env.AKS_CLUSTER_NAME }}

      - name: Deploy all manifests
        run: |
          echo "Deploying all services using release/kubernetes-manifests.yaml"
          kubectl apply -f release/kubernetes-manifests.yaml
          kubectl wait --for=condition=available --timeout=60s deployment --all --namespace ${{ env.AKS_NAMESPACE }}

      - name: Update images
        run: |
          for service in ${{ inputs.images }}; do
            echo "Updating image for $service"
            if [ "$service" == "cartservice" ]; then
              kubectl set image deployment/cartservice server=skilltechregistry.azurecr.io/cartservice:latest --namespace ${{ env.AKS_NAMESPACE }}
            else
              kubectl set image deployment/$service server=skilltechregistry.azurecr.io/$service:latest --namespace ${{ env.AKS_NAMESPACE }}
            fi
            echo "Updated $service"
          done
