name: Deploy to AKS

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches:
      - dev 
  workflow_dispatch: {} 

permissions:
  id-token: write
  contents: read

env:
  AKS_NAMESPACE: 'default' 
  ACR_NAME: 'skilltechregistry'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Get built images
        run: echo "${{ needs.build-and-push.outputs.images }}" 

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group microservices-demo-rg --name microservices-demo-aks --overwrite-existing

      - name: Install Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Deploy to AKS using Helm
        run: |
          for service in ${{ needs.build-and-push.outputs.images }}; do
            echo "Deploying $service"
            helm upgrade --install $service charts/$service \
              --set image.repository=${{ env.ACR_NAME }}.azurecr.io/$service \
              --set image.tag=latest \
              --namespace ${{ env.AKS_NAMESPACE }} 
            echo "Deployed $service"
          done

      - name: Azure CLI logout
        run: |
          az logout
