name: Deploy to AKS

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

env:
  AKS_NAMESPACE: 'default'
  ACR_NAME: 'skilltechregistry'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Verify Azure CLI installation
        run: |
          az --version

      - name: Log in to Azure
        uses: azure/login@v1.4.7
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group microservices-demo-rg --name microservices-demo-aks --overwrite-existing

      - name: Deploy all services
        run: |
          echo "Deploying all services using release/kubernetes-manifests.yaml"
          kubectl apply -f release/kubernetes-manifests.yaml

      - name: Update image tags for each service
        run: |
          echo "Updating image tags for all services to ${{ github.event.inputs.image_tag }}"
          kubectl set image deployment/currencyservice currencyservice=skilltechregistry.azurecr.io/currencyservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/adservice adservice=skilltechregistry.azurecr.io/adservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/cartservice cartservice=skilltechregistry.azurecr.io/cartservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/checkoutservice checkoutservice=skilltechregistry.azurecr.io/checkoutservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/emailservice emailservice=skilltechregistry.azurecr.io/emailservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/frontend frontend=skilltechregistry.azurecr.io/frontend:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/loadgenerator loadgenerator=skilltechregistry.azurecr.io/loadgenerator:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/paymentservice paymentservice=skilltechregistry.azurecr.io/paymentservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/productcatalogservice productcatalogservice=skilltechregistry.azurecr.io/productcatalogservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/recommendationservice recommendationservice=skilltechregistry.azurecr.io/recommendationservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/shippingservice shippingservice=skilltechregistry.azurecr.io/shippingservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}
          kubectl set image deployment/shoppingassistantservice shoppingassistantservice=skilltechregistry.azurecr.io/shoppingassistantservice:${{ github.event.inputs.image_tag }} --namespace ${{ env.AKS_NAMESPACE }}

      - name: Azure CLI logout
        run: |
          az logout

      - name: Azure CLI logout
        run: |
          az logout
